---
title: "Beyond the metropolises: the decentralization of chikungunya to non-metropolitan regions across Brazil."
author: "Iasmim Ferreira de Almeida, Cláudia Torres Codeço and Raquel Martins Lana"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Biblioteca

```{r, message = FALSE}
packages <- c("tidyverse", "geofacet", "sf")
invisible(install.packages(setdiff(packages, rownames(installed.packages()))))
invisible(lapply(packages, require, character.only = TRUE))

options(scipen = 999) # avoid scientific numbers

```

# Incidência e classificação dos municipios

## Incidência

```{r}
#load("../data/chikv_14_22_final.Rdata")

# Calculo da incidencia por ano por município
d_inc <- d_agreg %>% 
  group_by(CODE_MUNI, NAME_MUNI, ACR_UF, YEAR, POP) %>%
  summarise(CASESy = sum(CASES)) %>%
  mutate(INCy = CASESy/POP * 100000) 

# NA
d_inc %>% map(~mean(is.na(.)))

#observando
summary(d_inc$INCy) #maior incidência na série foi Fernando de Noronha 2021

```

## Incidencia por região metropolitana e não metropolitana

```{r}
# Ler os dados
reg_metr <- read_csv2("../tables/reg_metr_non_metr.csv")
str(reg_metr)
reg_metr %>% map(~mean(is.na(.)))
# Excluindo o Distrito Federal antes de juntar os bancos
d_inc <- d_inc %>% filter(CODE_MUNI != "530010")

class(reg_metr$CODE_MUNI)
reg_metr <- reg_metr %>% 
  filter(CODE_MUNI != 5300108) %>% 
  mutate(CODE_MUNI = as.character(CODE_MUNI),
         CODE_MUNI = str_sub(CODE_MUNI, 1, 6)) %>% # compatibilizando para juntar com d_inc
  rename(ACR_UF = STATE)

# Juntar os bancos de dados pelo CODE_MUNI _NAO DEU CERTO
d <- d_inc %>%
  left_join(reg_metr)
# NA
d %>% map(~mean(is.na(.)))

# Agrupar por HIERARQUIA (metropolitano ou não), REGION, STATE e YEAR
dmetrop <- d %>%
  group_by(regiao, REGION, ACR_UF, YEAR) %>%
  summarise(
    CASESrm = sum(CASESy),   # Total de casos na categoria
    POP_SIZErm = sum(POP)  # Total da população na categoria
  ) %>%
  ungroup() %>% 
  mutate(
    INCrm = (CASESrm / POP_SIZErm) * 100000, # Cálculo da incidência por 100 mil hab.
    HIERARCHY = regiao  # Renomeando a coluna 'regiao' para 'hierarquia'
  ) %>%
  select(HIERARCHY, REGION, ACR_UF, YEAR, CASESrm, POP_SIZErm, INCrm) # Selecionando as variáveis desejadas

dmetrop %>% map(~mean(is.na(.)))
summary(dmetrop)
              
save(dmetrop, file = "../tables/inc_reg_met.RData")

```

